services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "32770:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:32770/api
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
